"""
Processes error map scripts generated by pyNF2fF.py
"""

import FileReading.readFromFile as rff
import numpy as np
import matplotlib.pyplot as plt
import NF2FF.NFFFandFPlotting as plotting
import os

error_map_list = os.listdir("ErrorFields/")
for filename in error_map_list:
    print(filename)
    theta_grid, phi_grid, gain_grid = rff.read_farfield_gain_datafile("ErrorFields/"+filename)
    plotting.plot_nearfield_2d(theta_grid, phi_grid, 10*np.log10(gain_grid), filename, zlim=[-20,0])

plt.show()

